[versions]
advanced-runtime-resource-packs = "0.5.+"
enhancedblockentities = "0.6+1.18.2"
fabric-api = "0.51.1+1.18.2"
fabric-loader = "[0.14,1)"
intellij-fernflower = "1.+"
java = "17.+"
minecraft = "1.18.2"
modmenu = "[3.1,4)"
quiltflower = "1.+"
spruceui = "3.3.0+1.17"

[libraries]
advanced-runtime-resource-packs = { module = "net.devtech:arrp", version.ref = "advanced-runtime-resource-packs" }
enhancedblockentities = { module = "maven.modrinth:ebe", version.ref = "enhancedblockentities" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
intellij-fernflower = { module = "org.jetbrains:intellij-fernflower", version.ref = "intellij-fernflower" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
quiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }

[plugins]
fabric-loom = "fabric-loom:0.+"
loom-quiltflower = "io.github.juuxel.loom-quiltflower:1.+"
