[versions]
fabric-api = "0.51.1+1.18.2"
fabric-loader = "0.13.3"
fernflower = "5.2.1.Final"
minecraft = "1.18.2"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fernflower = { module = "org.jboss.windup.decompiler:decompiler-fernflower", version.ref = "fernflower" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

[plugins]
fabric-loom = "fabric-loom:0.11.+"
