[versions]
bedrockify = "1.4.1+mc1.18.2"
enhancedblockentities = "0.7.1+1.18.2"
fabric-api = "0.56.1+1.18.2"
fabric-loader = "latest.release"
fabric-loom = "latest.release"
iris = "1.18.x-v1.2.5"
lazydfu = "latest.release"
loom-quiltflower = "latest.release"
minecraft = "1.18.2"
modmenu = "3.2.+"
parchment = "2022.06.19"
quiltflower = "latest.release"
sodium = "mc1.18.2-0.4.1"
spruceui = "[3.3.3,4.0.0)"

[libraries]
bedrockify = { module = "maven.modrinth:bedrockify", version.ref = "bedrockify" }
enhancedblockentities = { module = "maven.modrinth:ebe", version.ref = "enhancedblockentities" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-loom = { module = "net.fabricmc:fabric-loom", version.ref = "fabric-loom" }
iris = { module = "maven.modrinth:iris", version.ref = "iris" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }
loom-quiltflower = { module = "io.github.juuxel:loom-quiltflower", version.ref = "loom-quiltflower" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
quiltflower = { module = "org.quiltmc:quiltflower", version.ref = "quiltflower" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
loom-quiltflower = { id = "io.github.juuxel.loom-quiltflower", version.ref = "loom-quiltflower" }
