name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        architecture: [ x86, x64, armv7, aarch64, ppc64le ]
        java: [ 17, 18, 19 ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          architecture: ${{ matrix.architecture }}
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Capture build artifacts
        if: ${{ runner.os == 'Windows' && matrix.architecture == 'x64' && matrix.java == '17' }} # Only upload artifacts built from one OS, architecture, and java version
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
