name: publish
on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version Type'
        required: false
        default: 'alpha'
        type: choice
        options:
         - release
         - beta
         - alpha

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Build
        run: ./gradlew build curseforge modrinth --stacktrace
        env:
          CURSEFORGE_API_KEY: $${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          VERSION_TYPE: ${{ inputs.versionType }}
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
